kind: ConfigMap
apiVersion: v1
metadata:
  name: hocs-converter
data:
  converter_timeout: '300000'
  max_filesize: '52428800'
  supported_types: 'doc,docx,txt,rtf,html,pdf,jpg,jpeg,tif,tiff,png,bmp,gif,xls,xlsx'
