---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hocs-frontend
  labels:
    version: {{.VERSION}}
spec:
  replicas: {{.REPLICAS}}
  selector:
    matchLabels:
      name: hocs-frontend
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hocs-frontend
        role: hocs-frontend
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:v0.0.6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=hocs-frontend.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy-govuk:v3.2.11
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
          requests:
            memory: 256Mi
            cpu: 150m
        env:
          - name: PROXY_SERVICE_HOST_1
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT_1
            value: '8081'
          - name: PROXY_SERVICE_HOST_2
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT_2
            value: '8082'
          - name: LOCATIONS_CSV
            value: '/, /api/'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
          - name: ERROR_REDIRECT_CODES
            value: '501 502 503 504'
          - name: ADD_NGINX_HTTP_CFG
            value: 'fastcgi_buffers 16 64k; fastcgi_buffer_size 128k; proxy_buffer_size 128k; proxy_buffers 4 64k; proxy_busy_buffers_size 128k; client_header_buffer_size 8k; large_client_header_buffers 4 128k;'
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name: keycloak-proxy-web
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.3.0
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
         limits:
          memory: "128Mi"
          cpu: 100m
         requests:
          memory: "64Mi"
          cpu: 50m
        args:
          - --config=/etc/secrets/data.yml
          - --discovery-url={{.KC_REALM}}
          - --openid-provider-proxy=http://hocs-outbound-proxy.{{.KUBE_NAMESPACE}}.svc.cluster.local:31290
          - --listen=127.0.0.1:8081
          - --enable-logging=true
          - --enable-json-logging=true
          - --upstream-url=http://127.0.0.1:8080 # app
          - --upstream-response-header-timeout=60s
          - --upstream-expect-continue-timeout=60s
          - --upstream-keepalive-timeout=60s
          - --server-read-timeout=60s
          - --server-write-timeout=60s
          - --no-redirects=false
          - --redirection-url=https://{{.DOMAIN_NAME}}
          - --cors-origins='*'
          - --resources=uri=/health|white-listed=true
          - --resources=uri=/public/*|white-listed=true
          - --resources=uri=/*
          - --secure-cookie=true
          - --http-only-cookie=true
          - --revocation-url={{.KC_REALM}}/protocol/openid-connect/logout
          - --enable-logout-redirect=true
          - --verbose
        ports:
          - name: keycloak-http
            containerPort: 8081
        volumeMounts:
          - mountPath: /etc/secrets
            name: frontend-keycloak-secret
            readOnly: true
      - name: keycloak-proxy-api
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.3.0
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
         limits:
          memory: "128Mi"
          cpu: 100m
         requests:
          memory: "64Mi"
          cpu: 50m
        args:
          - --config=/etc/secrets/data.yml
          - --discovery-url={{.KC_REALM}}
          - --openid-provider-proxy=http://hocs-outbound-proxy.{{.KUBE_NAMESPACE}}.svc.cluster.local:31290
          - --listen=127.0.0.1:8082
          - --enable-logging=true
          - --enable-json-logging=true
          - --upstream-url=http://127.0.0.1:8080 # app
          - --upstream-response-header-timeout=60s
          - --upstream-expect-continue-timeout=60s
          - --upstream-keepalive-timeout=60s
          - --server-read-timeout=60s
          - --server-write-timeout=60s
          - --no-redirects=true
          - --redirection-url=https://{{.DOMAIN_NAME}}
          - --cors-origins='*'
          - --resources=uri=/health|white-listed=true
          - --resources=uri=/public/*|white-listed=true
          - --resources=uri=/*
          - --secure-cookie=true
          - --http-only-cookie=true
          - --verbose
        ports:
          - name: keycloak-http
            containerPort: 8082
        volumeMounts:
          - mountPath: /etc/secrets
            name: frontend-keycloak-secret
            readOnly: true
      - name: hocs-frontend
        image: quay.io/ukhomeofficedigital/hocs-frontend:{{.VERSION}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        env:
          - name: PORT
            value: '8080'
          - name: NODE_ENV
            value: 'production'
          - name: GA_TRACKER
            valueFrom:
              secretKeyRef:
                name: hocs-frontend
                key: ga_tracker
          - name: USE_CLIENTSIDE
            valueFrom:
              configMapKeyRef:
                name: hocs-frontend
                key: clientside
          - name: MAX_UPLOAD_SIZE
            valueFrom:
              configMapKeyRef:
                name: hocs-converter
                key: max_filesize
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-untrusted-s3
                key: access_key_id
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-untrusted-s3
                key: secret_access_key
          - name: S3_REGION
            value: 'eu-west-2'
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-untrusted-s3
                key: bucket_name
          - name: S3_SSE_KEY
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-untrusted-s3
                key: kms_key_id
          - name: TRUSTED_S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-trusted-s3
                key: access_key_id
          - name: TRUSTED_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-trusted-s3
                key: secret_access_key
          - name: TRUSTESD_S3_REGION
            value: 'eu-west-2'
          - name: TRUSTED_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: {{.KUBE_NAMESPACE}}-trusted-s3
                key: bucket_name
          - name: WORKFLOW_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: ui-casework-creds
                key: plaintext
          - name: WORKFLOW_SERVICE
            value: 'https://hocs-workflow.{{.KUBE_NAMESPACE}}.svc.cluster.local'
          - name: CASEWORK_SERVICE
            value: 'https://hocs-casework.{{.KUBE_NAMESPACE}}.svc.cluster.local'
          - name: DOCUMENT_SERVICE
            value: 'https://hocs-docs.{{.KUBE_NAMESPACE}}.svc.cluster.local'
          - name: INFO_SERVICE
            value: 'https://hocs-info-service.{{.KUBE_NAMESPACE}}.svc.cluster.local'
          - name: OUTBOUND_PROXY
            value: 'http://hocs-outbound-proxy.{{.KUBE_NAMESPACE}}.svc.cluster.local:31290'
          - name: ALLOWED_FILE_EXTENSIONS
            valueFrom:
              configMapKeyRef:
                  name: hocs-converter
                  key: supported_types
        resources:
          limits:
            cpu: 450m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /certs
            name: certs
            readOnly: true
      volumes:
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
        - name: frontend-keycloak-secret
          secret:
            secretName: frontend-keycloak-secret
